language: ruby
sudo: false
cache: bundler
rvm:
- 2.2
before_install:
  - gem update --system
  - gem update --remote bundler
before_script:
 - chmod +x ./script/cibuild

script: ./script/cibuild
branches:
  only:
    - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

